### ISSUE TITLE
Publishing on crates.io

### ISSUE THREAD

**Issue by mosuka** [fulmicoton/kuromoji-rs#1]
Hi,
Do you have a plan to publishing on crates.io?

**Comment by fulmicoton** [comment]
Would you take over the project :) ?

**Comment by mosuka** [comment]
Oh... OK, I take over this project. What should I do?

**Comment by fulmicoton** [comment]
Fork it. A hard fork is ok.  (No need to link it to the current repo.)

Keep my name in the MIT License but add 2019 or whatever and then add your name there.
Ideally mention "fork from fulmicoton's project" on the README.md
Remove me from the authors in the `Cargo.toml`.

... and then it is all yours.
Feel free to break API, fix bugs, remove stuff, ... and publish it on crates.io under your name  :)

**Comment by mosuka** [comment]
Thanks. I'm so grateful to you for this opportunity :)
